# Generated by Django 6.0.4 on 2026-04-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_genre_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
    ]
