# Generated by Django 6.0.4 on 2026-04-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_genre_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.actor'),
        ),
    ]
