# Generated by Django 6.0.4 on 2026-04-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_alter_movie_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='studio',
            new_name='studio_name',
        ),
    ]
