# Generated by Django 6.0.4 on 2026-04-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_rename_studio_movie_studio_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='studio_name',
            new_name='studio',
        ),
    ]
