# Generated by Django 6.0.4 on 2026-04-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_rename_studio_name_movie_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tmdb_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
